version: "3.7"

services:
    db:
        image: postgres:11.5-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        command: python main.py
        volumes:
            - ./app/:/app/
        ports:
            - 8000:8000
        env_file:
            - .env.sample
        depends_on:
            - db

volumes:
    postgres_data:
